export const EXPERIENCES = [
  {
    year: "2025.09 - 2025.12",
    role: "Fullstack Developer",
    company: "TACO (China)",
    description_en: `I developed a desktop application using Electron. I was responsible for data visualization using nodes and edges with d3-force, implementing LLM-powered agent features, and managing a local database with Dexie.js. On the backend, I handled real-time chat functionality using Server-Sent Events (SSE) as well as user management features.`,
    description_ko: `Electron을 사용하여 데스크탑 애플리케이션을 구현했습니다. 3d-force를 사용하여 노드, 엣지를 통한 데이터 시각화, LLM을 통한 Agent 기능 및 dexie를 통해 로컬 DB 관리 기능을 담당했습니다. 백엔드에서는 SSE를 통한 채팅 기능, 유저 관리 기능을 담당했습니다.`,
    technologies: [
      "TypeScript",
      "React",
      "Electron",
      "IndexedDB",
      "Express.js",
      "MongoDB",
    ],
  },
  {
    year: "2024.05 - 2025.06",
    role: "Frontend Developer",
    company: "iStay (China)",
    description_en: `I was responsible for the development and maintenance of front-end for both web and mobile applications using TypeScript. Additionally, I continuously worked on improving the user experience (UX) and performed various tasks such as developing plugins and publishing components to npm for modifying iOS and Android native code.`,
    description_ko: `타입스크립트를 기반으로 Next.js와 React를 사용하여 웹 및 모바일 애플리케이션의 개발 및 유지 보수를 담당했습니다. 또한, 사용자 경험(UX)을 개선하고 다양한 작업을 수행하여 iOS 및 Android 네이티브 코드를 수정하기 위한 npm 플러그인 개발 및 게시판 구성 요소를 개발했습니다.`,
    technologies: [
      "TypeScript",
      "React",
      "NextJs",
      "TailwindCSS",
      "React Native",
      "Figma",
    ],
  },
  {
    year: "2025.07 - 2025.08",
    role: "Learner",
    company: "POSTECH@Apple Academy Foundation Program",
    description_en: `Responsible for backend architecture design and implementation, server deployment, and served as team leader overseeing frontend code reviews and project management.`,
    description_ko: `애플 아카데미에서 팀 단위 프로젝트를 진행할 때 백엔드 아키텍처 설계 및 구현, 서버 배포를 담당하였습니다. 또한 팀 리더로서 프론트엔드 코드 리뷰와 일정 및 커뮤니케이션 관리를 수행하며 팀 Tech Lead로 활동하였습니다.`,
    technologies: ["SwiftUI", "Django", "AWS"],
  },
  {
    year: "2020.02 - 2020.08",
    role: "Frontend Publisher",
    company: "TECO Education (Korea)",
    description_en: `I was responsible for the overall design and development of the company’s website in a resource-limited environment, handling everything from logo design to UI/UX design and implementing responsive web design.`,
    description_ko: `회사 소개 사이트의 디자인과 개발을 담당하였습니다. Figma와 Adobe Photoshop, Illustrator를 사용하여 로고 디자인에서 UI/UX 디자인까지 모든 디자인을 담당하고 TailwindCSS를 사용하여 반응형 웹을 구현하였습니다.`,
    technologies: [
      "React",
      "TailwindCSS",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Figma",
    ],
  },
];
